name: CI

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - 'v*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: yarn
      - name: Build, lint, and run unit tests
        run: yarn ci
      - name: Integration tests
        run: yarn test:integration
        env:
          SWID: ${{ secrets.SWID }}
          ESPN_S2: ${{ secrets.ESPN_S2 }}
          LEAGUE_ID: ${{ secrets.LEAGUE_ID }}
